# SITE CONFIGURATION
url: "https://seacho.github.io"

author: p1ain0
title:  kaka
#logo:   bazad.svg
description: "kaka maka baka"

excerpt_separator: "<!--more-->"

social:
  - icon:           rss
    url:            /feed.xml
    description:    RSS feed
  # - icon:           twitter
  #   url:            https://twitter.com/_bazad
  #   description:    Twitter
  - icon:           github
    url:            https://github.com/seacho
    description:    Github
  - icon:           envelope
    url:            mailto:assdfgzxcv4@gmail.com
    description:    Email

permalink: /:year/:month/:title/

paginate: 16
paginate_path: "page/:num"
post_navigation: true

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
